### ISSUE TITLE
New 1.7.10 update crashes on world load.

### ISSUE THREAD

**Issue by border999** [Hunternif/MosesMod#2]
http://pastebin.com/yjhjMp6Q

**Comment by Hunternif** [comment]
Thank you for reporting this. Although I couldn't reproduce the crash, this fix should solve it. Please try and see if it crashes again:
https://dl.dropboxusercontent.com/u/6746449/MosesMod/mosesmod-1.7.10-1.4.1.jar

**Comment by border999** [comment]
Confirmed, It no longer crashes. Thanks for the fix
